# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

doVB_pois <- function(y, X, Dim, L, iter, a, b, display_progress) {
    .Call(`_bigram2vec_doVB_pois`, y, X, Dim, L, iter, a, b, display_progress)
}

